name: Build Proxia APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le projet sans modifier les fichiers
        uses: actions/checkout@v4

      - name: Installer Java 17
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurer Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Construire Proxia
        run: |
          echo "Construction de Proxia..."
          gradle assembleDebug

      - name: Verifier que l'APK existe
        run: |
          echo "Recherche de l'APK..."
          find application/build/outputs/apk -type f -name "*.apk" -print

      - name: Recuperer l'APK
        uses: actions/upload-artifact@v4
        with:
          name: Proxia-APK
          path: application/build/outputs/apk/debug/application-debug.apk
